[package]
name = "dango_fn"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MrPicklePinosaur"]
description = "chatgpt powered voice assistant"
repository = "https://github.com/KaratsubaLabs/dango"

[dependencies]
serde_json = "1"
